default_platform(:ios)

platform :ios do
  desc "Upload an existing IPA to TestFlight"
  lane :testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    pilot(
      api_key: api_key,
      ipa: ENV["IPA_PATH"],
      skip_waiting_for_build_processing: true
    )
  end
end
